Clean pvServer.py
React-Automation-Studio/React-Automation-Studio pull request #47
Opened 2022-04-21 15:49 UTC by giosava94

Pull request to resolve #34.

Here what I did on `pvServer.py`:
- Removed the unnecessary empty lines
- Converted all commented print into log.debug
- Reordered imports
- Fix minor typos and moved some functions to group them by "topic" (pv, auth, database)
- Formatted text using black

I did not found useless function at the moment and I did not edit code in any way (apart from the initial log messages).
Let me know if there are too much changes, there is something else to change or something else.

Regards,
Giovanni

2022-04-22 07:22 UTC, hanak commented on pvServer/pvServer.py
> +            log.debug("password", LDAP_USER_PW)
If an exception occurs, this line dumps LDAP password in plain text to logs. This can compromise the the account in case logs leak. Would it be possible to remove this line, please?

2022-04-22 07:22 UTC, hanak commented on pvServer/pvServer.py
> +            log.debug("username", LDAP_USER_DN)
This line could contain personal data. Let us avoid logging it, please.

2022-04-22 08:55 UTC, hanak requested changes
Nice work. I have added some comments around logging potentially sensitive information. I think we should be careful. Let us update the code.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
>                  pass
This line is useless now.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +    log.debug("message:", str(message))
Given generic nature of the access point, this log might leak sensitive information or secrets to logs accidentally. Let us remove  it, please.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +                                log.debug("using query:", query)
This might leak sensitive information to logs. Can we remove the log message, please?

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +    log.debug("message:", str(message))
This log message might leak sensitive information to the logs. Can we remove it, please?

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +            log.debug("Parameters:", str(parameters))
Is there a chance this might leak sensitive information? If so, let us remove the log message.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +                                log.debug("using query:", query)
Can this leak sensitive information? If so, let us remove the log message.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
>                  pass
Useless line. Let us remove it.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +    log.debug("message:", str(message))
This might leak sensitive information. Please, remove.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +    log.debug("message:", str(message))
Could there be sensitive information? Is unsure, remove this log line, please.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +            log.debug(message)
Could this leak sensitive information? If unsure, let us remove the log message, please.

2022-04-22 08:55 UTC, hanak commented on pvServer/pvServer.py
> +    log.info("Error, old socket io authentication is disabled")
Can we use `log.error()`, please?

2022-04-27 11:20 UTC, giosava94 commented on pvServer/pvServer.py
> +        return jsonify({"login": False}), 401
Yes, it is black. On VSCode we have a shortcut that applies formatting (black formatting in this case) on all the code and this (replace `'` with `"`) is a common change it does.

2022-04-27 13:12 UTC, giosava94 commented on pvServer/pvServer.py
> +                                    .find(query, projection)
When I run black it automatically removes the indentation

2022-04-27 13:26 UTC, giosava94 commented on pvServer/pvServer.py
> +    log.info("Error, old socket io authentication is disabled")
I think this is an event that has been substituted. As a reminder, when a client generate the _AuthenticateClient_ event, the backend log this message and do nothing. With a quick research, I verified that this event is generated by no-one. I think this event handler can be removed.

2022-04-28 09:23 UTC, hanak commented on pvServer/pvServer.py
> +    log.info("Error, old socket io authentication is disabled")
I think this one is about backward compatibility because there not much control about their deployment. Maybe, this was meant to discover someone is using an older (outdated) client. Sadly, the log message does not hint where it is coming from (so the administrator can take an action). I think deleting it does not harm the solution. So, we can keep the change even though it goes beyond the scope of the item. Still, we should think about backward compatibility when making changes so that there is a clear upgrade path for the users which a user can do without a help-desk call or a special email notification. Otherwise, it will be a great source of frustration for everyone.

2022-04-28 09:24 UTC, hanak approved these changes
I think the update looks good. Let us get it in.

2022-04-28 09:25 UTC, merged